config/routes.rb
Boarder::Application.routes.draw do

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  # 
  # once a user has successfully signed in
  # a redirection from routes /users to /account happens
  #   
  devise_for :users, skip: [:registrations], 
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get    '/users/sign_up(.:format)', to: 'devise::registrations#new',    as: :new_user_registration
    post   '/users(.:format)',         to: 'devise::registrations#create', as: :user_registration
    get    '/account/edit(.:format)',  to: 'devise::registrations#edit',   as: :edit_account
    put    '/account(.:format)',       to: 'devise::registrations#update', as: :account
    get    '/users/cancel(.:format)',  to: 'devise::registrations#cancel', as: :cancel_user_registration
    delete '/users(.:format)',         to: 'devise::registrations#destroy'
  end

  get '/admin(.:format)', to: 'users#index', as: :admin
  get '/account(.:format)', to: 'users#show', as: :user_root

  # take a tour for demo
  get '/account(.:format)/tour', to: 'users#tour', as: :account_tour

  scope 'account' do
    resources :projects do
      resource :team, only: [:create, :show]    
      resources :records, only: [:create]
    end
    resource :submission, only: [:show]
  end

  #get '/about', to: 'about#index', as: :about
end

app/views/shared/_account_nav.html.erb
<div id="account-sidebar" class="span2 bs-docs-sidebar">
  <ul id="account-sidenav" class="nav nav-list bs-docs-sidenav affix">
    <li class="nav-header">Account</li>
    <li><%= link_to raw('<i class="icon-home"></i> Home'), account_path %></li>
    <li><%= link_to raw('<i class="icon-user"></i> Profile'), edit_account_path %></li>
    <li class="divider"></li> 
    <li class="nav-header">Project</li>
    <li><%= link_to raw('<i class="icon-list"></i> All'), projects_path %></li>
    <li><%= link_to raw('<i class="icon-plus"></i> New'), new_project_path %></li>
    <li class="divider"></li> 
    <li class="nav-header">Quick</li>
    <li><%= link_to raw('<i class="icon-circle-arrow-right"></i> Submission'), submission_path %></li>
    <% if !@navigation_tags.nil? %>
      <li class="divider"></li> 
      <li class="nav-header">Navigation Tag</li> 
      <li><a href="#"><i class="icon-circle-arrow-right"></i> Page Top</a></li>
      <li><a href="#activities"><i class="icon-circle-arrow-right"></i> Activities</a></li>
      <li><a href="#charts"><i class="icon-circle-arrow-right"></i> Charts</a></li>  
      <li><a href="#tool-box"><i class="icon-circle-arrow-right"></i> Tool Box</a></li>
      <li class="divider"></li> 
      <li><%= link_to raw('<i class="icon-pencil"></i> Edit'), edit_project_path %></li>
    <% end %>
  </ul>
</div>