config/routes.rb
Boarder::Application.routes.draw do

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  # 
  # once a user has successfully signed in
  # a redirection from routes /users to /account happens
  #   
  devise_for :users, skip: [:registrations], 
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get    '/users/sign_up(.:format)', to: 'devise::registrations#new',    as: :new_user_registration
    post   '/users(.:format)',         to: 'devise::registrations#create', as: :user_registration
    get    '/account/edit(.:format)',  to: 'devise::registrations#edit',   as: :edit_account
    put    '/account(.:format)',       to: 'devise::registrations#update', as: :account
    get    '/users/cancel(.:format)',  to: 'devise::registrations#cancel', as: :cancel_user_registration
    delete '/users(.:format)',         to: 'devise::registrations#destroy'
  end

  get '/admin(.:format)', to: 'users#index', as: :admin
  get '/account(.:format)', to: 'users#show', as: :user_root

  # take a tour for demo
  get '/account(.:format)/tour', to: 'users#tour', as: :account_tour

  scope 'account' do
    resources :projects do
      resource :team, only: [:create, :show]    
      resources :records, only: [:create]
    end
    resource :submission, only: [:show]
  end

  #get '/about', to: 'about#index', as: :about
end

app/models/project.rb
class Project < ActiveRecord::Base
  # attributes
  attr_accessible :name, :description, :manager, :due_at

  # validations
  validates_presence_of :name

  # model hooks
  # project should not be destroied
  has_and_belongs_to_many :users, join_table: :users_projects
  has_many :tasks, dependent: :destroy
  has_many :records, through: :tasks
  has_many :invitations, dependent: :destroy

  # callbacks
  before_save :fill_due_at

  def percent
    percent = (((Time.now - created_at)/(due_at - created_at))*100).to_i
    percent > 100 ? 100 : percent
  end

  private
  
  def fill_due_at
    self.due_at = due_at.end_of_day
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /projects
  def index
    @user = current_user
    @in_progress_projects = @user.in_progress_projects
    @history_projects = @user.history_projects
  end

  # GET /projects/1
  def show    
    @project = Project.find(params[:id])
    @leader = @project.users.find_by_name(@project.manager)
    @members = @project.users.where("name!=?", @project.manager)
    @tasks = [Task.new] + @project.tasks
    @record = Record.new
    # decide whether or not to display navigation tags
    @navigation_tags = !nil

    respond_to do |format|
      format.html { render action: 'show' }
      format.json { render json: charts_data_for(@project) } 
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
    @tasks = [Task.new]
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    @tasks = @project.tasks
  end

  # POST /projects
  def create
    initiate_params
    if project_saved?
      redirect_to @project, notice: "Project was successfully created."
    else
      prepare_params_for_view 
      render action: 'new'
    end
  end

  # PUT /projects/1
  def update
    initiate_params
    if project_saved?
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      prepare_params_for_view
      render action: 'edit'
    end
  end

  # DELETE /projects/1
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully deleted.'
  end

  private
  
  #
  # categorize params
  #
  def initiate_params
    @project_params = params[:project]
    @tasks_params = @project_params.delete(:task)
    @tasks_params.each do |i, task_params|      
      task_params[:tag] = i
    end
    # instance parameters
    @user = current_user
    @project = @user.projects.where(id: params[:id]).first
    @project = Project.new(@project_params) if @project.nil?
  end

  #
  # true if the project and all tasks are saved
  # false otherwise
  #
  def project_saved?
    begin  
      @project.transaction do
        # validations
        ensure_unique_project_name!
        ensure_unique_tasks_names!  
        # save
        save_project!
        save_tasks!
      end
      return true  
    rescue Exception => e
      return false
    end 
  end

  #
  # create or update project as needed
  #
  def save_project!
    #
    # use "@user.project.create" creates contract besides project
    # given "@user.project.build"+"@project.save" does not create contract
    # since we have a separate model contract ...
    #     
    @project.id.nil? ? @project = @user.projects.create!(@project_params) : @project.update_attributes!(@project_params)
  end

  #
  # create or update tasks as needed
  # project should have a valid id
  #
  def save_tasks!    
    @tasks_params.each do |i, task_params|
      # primary key, only one task expected
      task = Task.where("project_id=? and tag=?", @project.id, i).first
      task.nil? ? @project.tasks.create!(task_params) : task.update_attributes!(task_params)
    end
  end

  #
  # project names are forced unique for single user
  # however, they are allowed duplicated among different users 
  #
  def ensure_unique_project_name!
    dup_name_projects = @user.projects.where("name=?", @project.name)
    dup_name_projects.each do |project|
      raise RuntimeError, 'Duplicated project name' if project.id != @project.id
    end
  end

  #
  # tasks names are forced unique for single project
  # however, they are allowed duplicated among different projects 
  #
  def ensure_unique_tasks_names! 
    for i in 0..(@tasks_params.count-2)
      for j in (i+1)..(@tasks_params.count-1)
        raise RuntimeError, 'Duplicated tasks names' if @tasks_params[i.to_s][:name] == @tasks_params[j.to_s][:name]
      end
    end
  end

  #
  # fill form with user inputs
  #
  def prepare_params_for_view
    # parameters used when render views 
    @project = Project.new(@project_params)
    @tasks = []
    @tasks_params.each do |i, task_params|
      @tasks << Task.new(task_params)
    end
  end

  #
  # prepare charts data for a specific project
  #
  def charts_data_for(project)
    charts_data = {}

    ### chart project hours ###    

    # time period
    from = project.created_at.to_date
    to = project.due_at.to_date + 1.week
    charts_data[:project_hours_from] = from 
    charts_data[:project_hours_to] = to

    # prepare data  
    charts_data[:project_hours] = groups_total_hours(project.records, from, to, 30) 

    ### chart tasks span ###

    # time period
    from = project.created_at.to_date
    to = project.due_at.to_date + 1.week
    charts_data[:tasks_span_from] = from 
    charts_data[:tasks_span_to] = to

    # prepare data 
    tasks_span = []
    tasks = project.tasks
    tasks.each do |task|
      records = task.records
      #
      # task expected time span from task creation to due
      # task practical time span from first record creation to last record creation
      #
      tasks_span << {task: 'Task '+(task.tag+1).to_s, create: task.created_at.to_date, due: task.due_at.to_date,
        start: records.minimum("created_at").to_date, finish: records.maximum("created_at").to_date}
    end

    # add extra data for the whole project
    records = project.records
    tasks_span.unshift({task: 'Project', create: project.created_at.to_date, due: project.due_at.to_date,
      start: records.minimum("created_at").to_date, finish: records.maximum("created_at").to_date})

    charts_data[:tasks_span] = tasks_span

    ### chart tasks hours ###

    # prepare data 
    tasks_hours = []
    #
    # at least one task has to be specified on the project creation
    #
    tasks = project.tasks
    tasks.each do |task|
      tasks_hours << {task: task.name, total_hours: task.records.sum("hours")}
    end
    charts_data[:tasks_hours] = tasks_hours

    ### chart tasks submission ###

    # time period
    from = project.created_at.to_date
    to = project.due_at.to_date + 1.week
    charts_data[:tasks_submission_from] = from 
    charts_data[:tasks_submission_to] = to

    # prepare data 
    tasks_submission = []
    #
    # at least one task has to be specified on the project creation
    #
    tasks = project.tasks
    tasks.each do |task|
      # records (submitted by all team members) are grouped with task
      records = task.records.where("records.created_at >= ?", from)
      records.each do |record|
        tasks_submission << {task: task.name, date: record.created_at.to_date, 
          time: record.created_at.strftime("%H-%M-%S"), hours: record.hours}
      end
    end
    charts_data[:tasks_submission] = tasks_submission

    charts_data.to_json
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  #
  # mark with additional icon if current_user is the team leader
  #
  def smart_link_to(project)
    html = ""
    if current_user.is_leader? project
      html = '<p>'+(link_to raw(project.name+' <i class="icon-map-marker blue"></i>'), project)+'</p>'
    else      
      html = '<p>'+(link_to project.name, project)+'</p>'
    end
    html.html_safe
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for @project, html: {class: "form-horizontal"} do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <fieldset class="project-info">
      <legend>Project</legend>
      <%= f.input :name, autofocus: true, required: false %>
      <%= f.input :description, required: false %>
      <%= f.input :due_at, as: :date, required: false %>
    </fieldset>
    <% @tasks.each_index do |i| %>
    <fieldset class="task-info">
      <legend>Task</legend>
      <%= f.simple_fields_for 'task[]', @tasks[i], index: i do |task_f| %>
      <%= task_f.input :name, required: false %>
      <%= task_f.input :due_at, as: :date, required: false %>
      <% end %>
    </fieldset>
    <% end %>
    <p><a class="new-task" href="#">Add more</a></p>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary", type: "button" %>
  </div>
<% end %>

app/views/projects/_history.html.erb
<table class="table table-striped no-padding">
  <thead>    
    <tr>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @history_projects.in_groups_of(4, false) do |projects| %>
      <tr>
        <% projects.each do |project| %>      
          <td><%= smart_link_to project %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>  
</table>

app/views/projects/_progress.html.erb
<div class="row-fluid">
  <% @in_progress_projects.each do |project| %>
    <div class="span6">      
      <h4><%= smart_link_to project %></h4>
      <div class="progress">       
        <div class="bar" style="width: <%= project.percent %>%;"></div>
      </div>
    </div> 
  <% end %>
</div>

app/views/projects/_project.html.erb
<div class="div-list">
  <div class="row-fluid">
    <div class="span3">
      <p><b>Tasks</b></p>
      <% @tasks.each do |task| %>
        <p><%= task.name %></p>
      <% end %>
    </div>
    <div class="span3 offset3">
      <p><b>Leader</b></p>
      <p><%= @leader.name %></p>
      <p><b>Members</b></p>
      <% @members.each do |member| %>
        <p><%= member.name %></p>
      <% end %>
    </div>   
  </div>
</div>

app/views/projects/_record.html.erb
<%= simple_form_for @record, url: project_records_path(@project), defaults: { required: false }, html: { class: "form-horizontal"} do |f| %>
  <div class="form-inputs">
    <div class="row-fluid">
      <div class="span6">
        <div class="control-group string optional">
          <%= label_tag "task", "Tasks", class: "string optional control-label"%>
          <div class="controls">
          <%= select_tag "task", options_from_collection_for_select(@tasks, "id", "name") %>
          </div>
        </div>
        <%= f.input :hours %>
        <%= f.input :description %>
      </div>
      <div class="span6">
        <p>Submit daily work here</p>
      </div>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn btn-primary", type: "button" %>
  </div>
<% end %>

app/views/projects/_team.html.erb
<%= form_tag project_team_path(@project), class: "form-horizontal" do %>  
  <div class="form-inputs">
    <div class="row-fluid">
      <div class="span6">
        <div class="email-info">
          <div class="control-group string optional">
            <%= label_tag "email_0", "Email", class: "string optional control-label"%>
            <div class="controls">
            <%= text_field_tag "email[0]", "", id: "email_0" %>
            </div>
          </div>
        </div>  
        <p><a class="new-email" href="#">Add more</a></p>
      </div>
      <div class="span6">
        <p>Invite collaborators via sending them emails</p>
      </div>
    </div>
  </div>
  <div class="form-actions">
    <%= submit_tag "Send Emails", class: "btn btn-primary", type: "button" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="row-fluid">
  <%= render "shared/account_nav" %>
  <div class="span10">
    <%= render 'form' %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="row-fluid">
  <%= render "shared/account_nav" %>
  <div class="span10">
    <section class="section-fieldset">
      <fieldset>
        <legend>In progress</legend>        
        <%= render "progress" %>
      </fieldset>
    </section>
    <section class="section-fieldset">
      <fieldset>
        <legend>History</legend>   
        <%= render "history" %>        
      </fieldset>
    </section>
  </div>
</div>

app/views/projects/new.html.erb
<div class="row-fluid">
  <%= render "shared/account_nav" %>
  <div class="span10">
    <%= render 'form' %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row-fluid">
  <%= render "shared/account_nav" %>
  <div class="span10">
    <section class="section-fieldset">
      <fieldset>
        <legend><%= @project.name.upcase %></legend>
        <p><%= @project.description %></p>  
        <%= render "project" %>
      </fieldset>
    </section> 
    <section id="activities" class="section-fieldset">
      <fieldset>
        <legend>Activities</legend> 
        <%= render "log" %>
      </fieldset>
    </section>  
    <section id="charts" class="section-fieldset">
      <fieldset>
        <legend>Charts</legend>
        <div class="div-chart" id="chartset-project-hours"></div>
        <div class="div-chart" id="chartset-tasks-span"></div>
        <div class="div-chart" id="chartset-tasks-hours"></div>
        <div class="div-chart" id="chartset-tasks-submission"></div>
      </fieldset>  
    </section>  
    <section id="tool-box" class="section-fieldset">
      <fieldset>
        <legend>Tool Box</legend>
        <%= render "team" %>
        <%= render "record" %>
      </fieldset>
    </section>
  </div>
</div>